// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBhChKRikjuP6IPHlnrPZoBTY0iijC5_gY',
    appId: '1:93289255127:web:8e1976eee5c4176ba86092',
    messagingSenderId: '93289255127',
    projectId: 'capstone-career-ready-app',
    authDomain: 'capstone-career-ready-app.firebaseapp.com',
    storageBucket: 'capstone-career-ready-app.firebasestorage.app',
    measurementId: 'G-XD00CHNB5W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC8zumK2hYBkc6_nI0foTce3Gg9mAhKopY',
    appId: '1:93289255127:android:e4907b68162d0f18a86092',
    messagingSenderId: '93289255127',
    projectId: 'capstone-career-ready-app',
    storageBucket: 'capstone-career-ready-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD3-TnJ070q4vFblLEt7ZdBv1mlvUTLBUU',
    appId: '1:93289255127:ios:563b9eb735e657e4a86092',
    messagingSenderId: '93289255127',
    projectId: 'capstone-career-ready-app',
    storageBucket: 'capstone-career-ready-app.firebasestorage.app',
    iosClientId: '93289255127-sos826fr3befpgm8pi7sbs3ah0ufvadh.apps.googleusercontent.com',
    iosBundleId: 'com.captone.careerprep.mobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD3-TnJ070q4vFblLEt7ZdBv1mlvUTLBUU',
    appId: '1:93289255127:ios:563b9eb735e657e4a86092',
    messagingSenderId: '93289255127',
    projectId: 'capstone-career-ready-app',
    storageBucket: 'capstone-career-ready-app.firebasestorage.app',
    iosClientId: '93289255127-sos826fr3befpgm8pi7sbs3ah0ufvadh.apps.googleusercontent.com',
    iosBundleId: 'com.captone.careerprep.mobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBhChKRikjuP6IPHlnrPZoBTY0iijC5_gY',
    appId: '1:93289255127:web:8357a9ecaaf154f4a86092',
    messagingSenderId: '93289255127',
    projectId: 'capstone-career-ready-app',
    authDomain: 'capstone-career-ready-app.firebaseapp.com',
    storageBucket: 'capstone-career-ready-app.firebasestorage.app',
    measurementId: 'G-XB8JW3VFHF',
  );
}
